require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance

AllCops:
  NewCops: enable

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

RSpec/ExampleLength:
  Exclude:
    - 'spec/**/*.rb'

RSpec/ContextWording:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/NestedGroups:
  Max: 4

Layout/LineLength:
  Max: 200

Performance/MethodObjectAsBlock:
  Enabled: false

Metrics/AbcSize:
  Max: 30

Metrics/MethodLength:
  Max: 40

Metrics/PerceivedComplexity:
  Max: 14

Metrics/CyclomaticComplexity:
  Max: 15