# fly.toml app configuration file generated for slack-calc-bot on 2024-03-16T13:21:59-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = '<APP-NAME>'
primary_region = 'sjc2'
kill_signal = 'SIGINT'
kill_timeout = '5s'

[build]
  dockerfile = 'Dockerfile'

[env]
  LANG = 'en_US.UTF-8'
  MALLOC_ARENA_MAX = '2'
  PORT = '8080'
  RACK_ENV = 'production'
  RAILS_ENV = 'production'
  RAILS_LOG_TO_STDOUT = 'enabled'

[[services]]
  protocol = 'tcp'
  internal_port = 8080
  processes = ['app']

[[services.ports]]
    port = 80
    handlers = ['http']
    force_https = true

[[services.ports]]
    port = 443
    handlers = ['tls', 'http']

  [services.concurrency]
    type = 'connections'
    hard_limit = 25
    soft_limit = 20

[[services.tcp_checks]]
    interval = '15s'
    timeout = '2s'
    grace_period = '1s'
